- hosts: localhost
  tasks:

      - name: Test that my module works
        synchronize: 
            src: /home/dan/Downloads/alertsite-desktop-proxy-master
            dest: /home/dan/Documents/alertsite-desktop-proxy-master
        register: result
  
      - debug: var=result   
